Thesis.pdf: Thesis.tex Thesis.toc __commands.tex __environments.tex __tum.tex __tumtitle.tex Chapter_Change_of_coordinates.tex Beweis.tex Preparation.tex
	pdflatex Thesis

Thesis.toc: Thesis.tex
	pdflatex Thesis
